services:
  postgres:
    image: postgres:17.2
    container_name: postgresdb
    ports:
      - "5432:5432"
    env_file: ./backend/.env
    volumes:
      - ./backend/postgres:/var/lib/postgresql/data
  #docker compose up -d
