services:
  postgres:
    image: postgres:17.2
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    env_file: ./backend/.env
    volumes:
      - ./backend/postgres:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: prod
      dockerfile: Dockerfile
    image: gregoarcenta/devtalles-blog-backend:1.0.7
    container_name: backend
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      target: prod
      dockerfile: Dockerfile
    image: gregoarcenta/devtalles-blog-frontend:1.0.0
    container_name: frontend
    env_file: ./frontend/.env
    ports:
      - "3001:3000"
    depends_on:
      - backend
  #docker compose -f docker-compose.prod.yml up --build -d
